### PR TITLE
Improve Zabbix API datasource

### PR DESCRIPTION
**Pull request by alexanderzobnin**
Build off @christianchristensen and @nucleusv Zabbix API datasource.

2015-05-04 16-24-24 grafana - zabbix datasource - mozilla firefox

Query editor improvements: add host group, host, application and item selection from dropdown menu.

Support authentication by username and password:
```javascript
datasources: {        
        zabbix: {
          type: 'ZabbixAPIDatasource',
          url: 'http://www.zabbix.org/zabbix/api_jsonrpc.php',
          username: 'guest',
          password: '',
        }
      },
```

Fix problem with hardcoded history type in history request - now work with different data types.

This datasource work fine in grafana-1.9.1

### CODE REVIEW

**Comment by christianchristensen** [comment]
Very nice @alexanderzobnin ! Thank you!

I loaded up this latest PR in http://imetchrischris.com/grafana-plugins and a couple of observations:

*  Looks like on the initial load there's no datapoints (if you click the refresh button they'll populate)
*  When looking longer time ranges (7d) it looks like the datapoints shown are in the wrong time (see attached image)


Thinking-out-loud: should the dashboard save all of the Zabbix specific info in the dahsboard JSON (since that can be queried)? It it possible to get away with storing only the itemid and then performing the lookups for the hostname, etc. through the API?

screen shot 2015-05-03 at 7 33 03 pm

**Comment by alexanderzobnin** [comment]
Thanks, @christianchristensen. Yes, the first observation is the problem. I try to get zabbix auth token when datasource initialize. But this occurs asynchronously, and i don't know exactly when the variable is initialized. I'll try to solve this problem.
About second observation - it's not a problem. This is due to the parameter limitmetrics set to 5000 by default. I'll remove this default limitation.
And about the third - dashboard store targets with all specific info, like this:
```
"targets": [
            {
              "function": "mean",
              "column": "value",
              "host": {
                "hostid": "10005",
                "name": "Zabbix.org"
              },
              "errors": {},
              "item": {
                "itemid": "501",
                "name": "CPU $2 time ($3)",
                "key_": "system.cpu.util[,idle,avg1]",
                "value_type": "0",
                "delay": "60",
                "expandedName": "CPU idle time (avg1)"
              },
              "alias": "idle",
              "hostGroup": {
                "groupid": "2",
                "name": "Linux servers"
              },
              "application": {
                "applicationid": "27",
                "name": "CPU"
              }
            },
```
It's reduce number of requests to api and i think it's better way. Also, if you select All in host group and application, how to figure out it? And item may belong to several applications.

P.s. Sorry for my English, I have little practice in this field :)

**Comment by nucleusv** [comment]
@alexanderzobnin 
look at https://github.com/grafana/grafana-plugins/pull/10#issuecomment-87355168 

you need to check first have you authed already if yes just need do a query, if not, first get auth token

ZabbixAPIDatasource.prototype.query = function(options) {
      // get from & to in seconds
      var from = kbn.parseDate(options.range.from).getTime();
      var to = kbn.parseDate(options.range.to).getTime();
      var queries = '';//_.compact(_.map(options.targets, convertTargetToQuery));
      var result ='';
      var self = this;

      self.options = options;

      if(this.zabbix_api.token === null){
          result = this.zabbixAPILoginIn().then(function(response){
                 self.zabbix_api.token = response.data.result;
                 return self.performTimeSeriesQuery(queries, self.options, from, to);
          });
      }
      else {
          result = this.performTimeSeriesQuery(queries, this.options, from, to);
      }

      return result.then(handleZabbixAPIQueryResponse);
};

ZabbixAPIDatasource.prototype.zabbixAPILoginIn = function(){

     var request = {
          "jsonrpc": "2.0",
          "method": "user.login",
          "params": {
              "user": this.user,
              "password": this.password
          },
          "id": ++this.zabbix_api.request_count,
          "auth": null
      }

      return $http.post(this.url,request,this.config);
  }

**Comment by alexanderzobnin** [comment]
@nucleusv Thanks! It's work fine. I fixed authorization and now everything looks good.

**Comment by christianchristensen** [comment]
I just loaded the latest, this LGTM (looks good to me).

**Pull request merged**
