### PR TITLE
Atlas datasource plugin for Grafana 2.6

### PR DESCRIPTION
**Pull request by ivanarkhipov**
Atlas plugin for Grafana 2.6 is based on [older Atlas plugin implementation](https://github.com/grafana/grafana-plugins/tree/master/datasources/atlas).
Plugin presents 2 ways of input an Atlas query: simple query builder UI and raw query input.
Atlas response data format is configurable in _plugins.json_ file. More info in _README.md_ file.

This pull request is a part of Upwork.com contribution to Grafana project.

### CODE REVIEW

**Comment by ivanarkhipov** [comment]
#64

**Comment by pparth** [comment]
+1

**Comment by ivanarkhipov** [comment]
@torkelo Hello. Could you please take a look?

**Comment by torkelo** [comment]
this should be moved to it's own repo, then it could be added to http://grafana.net

**Comment by ivanarkhipov** [comment]
@torkelo Hello. Atlas plugin was moved to [this repo](https://github.com/upwork/grafana-atlas-datasource).
Please let me know if I need to provide more details about plugin in order to add it to http://grafana.net
Thanks.

**Comment by torkelo** [comment]
suibmit PR here, https://github.com/grafana/grafana-plugin-repository

**Comment by ivanarkhipov** [comment]
PR has been created - https://github.com/grafana/grafana-plugin-repository/pull/20

**Pull request merged**
