### PR TITLE
Add Monasca datasource

### PR DESCRIPTION
**Pull request by rbak1**
Adds a datasource for OpenStack's monitoring service, Monasca.

### CODE REVIEW

**Comment by haad** [comment]
+1 this would be nice to get merge any problems with this PR ?

**Comment by torkelo** [comment]
will close, this repo is deprecated (plugins should live in seperate repos)

**Comment by rbak1** [comment]
This datasource has been moved here:  https://github.com/openstack/monasca-grafana-datasource

**Comment by mtanda** [comment]
don't you add the monasca plugin to grafana.net?

**Comment by rbak1** [comment]
Yes, but that requires setting up a repo for the datasource. I just wanted to leave a note here so that anybody looking at the patch would know where it had moved.

**Comment by mtanda** [comment]
I got it. Thanks for your work to support Grafana 3.x 👍

**Pull request closed without merging**
