### PR TITLE
Druid Plugin for Grafana 3.0

### PR DESCRIPTION
**Pull request by abhisant**
Creating a Pull Request for the Druid Plugin which works on Grafana 3.0. I took an existing Druid Plugin which used to work on Grafana 2.6 and made changes to have it work on Grafana 3.0.

To test this plugin, this needs to be built with the Grafana 3.0 source code using grunt. It will produce all the map, js and ts files like following. These files can be copied to the grafana binary plugins/datasource/druid directory to have it work.

config_ctrl.d.ts
datasource.d.ts
module.js
plugin.json
query_ctrl.ts
config_ctrl.js
datasource.js
module.js.map
query_ctrl.d.ts
config_ctrl.js.map
img/
module.ts
query_ctrl.js
config_ctrl.ts
module.d.ts
partials/
query_ctrl.js.map

### CODE REVIEW

**Comment by torkelo** [comment]
We need to move the druid plugin to its own repo, the it can be listed on grafana.net, anyone that wants to own that repo?

**Comment by abhisant** [comment]
Yes, I can do that.

I will move it to a new repository and will get back to you by tomorrow.

I can own this repository and make it open for people to contribute.

One question, should I keep only the source code of plugin in the repo? Or
should I also place the plugin generated after the Build (which can
directly be copied to plugins repository to have it work).

Thank you,
Abhishek

On Thursday, June 30, 2016, Torkel Ödegaard <notifications@github.com>
wrote:

> We need to move the druid plugin to its own repo, the it can be listed on
> grafana.net, anyone that wants to own that repo?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/grafana-plugins/pull/76#issuecomment-229847965>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF098F8rhcZmUzh37WaRbjatggQXmaL1ks5qRI7MgaJpZM4I8QzS>
> .
>


-- 
Thank you
Abhishek Sant

**Comment by torkelo** [comment]
The plugin repo needs to contain the source and the build (if you use es6 or typescript), look at other plugin  repositories under grafana org

**Comment by abhisant** [comment]
Okay. Thanks for the quick response. Will create a repository under
github.com, and push the changes there. Will send you the repository link
once I am done, mostly by tomorrow.

Thanks again.

On Thursday, June 30, 2016, Torkel Ödegaard <notifications@github.com>
wrote:

> The plugin repo needs to contain the source and the build (if you use es6
> or typescript), look at other plugin repositories under grafana org
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/grafana/grafana-plugins/pull/76#issuecomment-229849141>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF098OB-FmMPc1BH9_YwwHumVBrgBHQAks5qRJHRgaJpZM4I8QzS>
> .
>


-- 
Thank you
Abhishek Sant

**Comment by torkelo** [comment]
will close, this repo is depricated

**Comment by abhisant** [comment]
Hi Torkel,

I have created the following opensource github repository for
grafana-druid-plugin, which contains the src and executable files and
README.md.

https://github.com/grafana-druid-plugin/druidplugin

Please let me know if you have any further questions.

Thank you,
Abhishek Sant

On Thu, Jun 30, 2016 at 9:06 PM, abhishek sant <abhisant@gmail.com> wrote:

> Okay. Thanks for the quick response. Will create a repository under
> github.com, and push the changes there. Will send you the repository link
> once I am done, mostly by tomorrow.
>
> Thanks again.
>
> On Thursday, June 30, 2016, Torkel Ödegaard <notifications@github.com>
> wrote:
>
>> The plugin repo needs to contain the source and the build (if you use es6
>> or typescript), look at other plugin repositories under grafana org
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/grafana/grafana-plugins/pull/76#issuecomment-229849141>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/AF098OB-FmMPc1BH9_YwwHumVBrgBHQAks5qRJHRgaJpZM4I8QzS>
>> .
>>
>
>
> --
> Thank you
> Abhishek Sant
>
>


-- 
Thank you
Abhishek Sant

**Comment by abhisant** [comment]
Replied on the sent email (adding Torkel).

**Comment by abhisant** [comment]
Hi Torkel,

Did you get a chance to look into the Druid Plugin repository.

https://github.com/grafana-druid-plugin/druidplugin <https://github.com/grafana-druid-plugin/druidplugin>

Thank you,
Abhishek Sant

**Pull request closed without merging**
