### PR TITLE
prometheus: Fix template variable query. Interpolate variables.

### PR DESCRIPTION
**Pull request by dln**
My first attempt at making template variable queries work, and properly interpolate variables inside the queries themselves.

Seems to work ok with Prometheus 0.15.1

### CODE REVIEW

**Comment by torkelo** [comment]
can you rebase this? seems to have conflicts

**Comment by marceldegraaf** [comment]
Any chance of getting this merged in @torkelo? Thanks!

**Comment by torkelo** [comment]
it againtst master, should be against prometheus branch?

**Comment by mtanda** [comment]
@marceldegraaf the changes is already merged to Grafana prometheus branch by jimmidyson.
https://github.com/grafana/grafana/blob/0c222c4e8c14b11046ce06f43e5e80f479283d51/public/app/plugins/datasource/prometheus/datasource.js#L198-L200

According to this comment, it will be available in next Grafana release.
https://github.com/grafana/grafana/pull/2847#issuecomment-144149533

**Pull request closed without merging**
