### PR TITLE
[prometheus] Step calculation needs to err on the large side, so s/floor/ceil

### PR DESCRIPTION
**Pull request by jmcfarlane**

### CODE REVIEW

**Comment by dan-cleinmark** [comment]
:+1: 

A little more detail on this - the main fix is on line 109.  Using a 2 week window (1209600 seconds) and a 60s step, Math.floor() recalculates a step of 109 and results in 11097 data points in the Prometheus query (> the 11000 max set by Prometheus).  Math.ceil() returns a step of 110 and 10996 data points.

**Comment by mtanda** [comment]
Thanks for fix this.
The Prometheus plugin is already merged to here.
https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource/prometheus

Please pull request to grafana/grafana repository.

**Comment by dan-cleinmark** [comment]
Thanks @mtanda.  I've created https://github.com/grafana/grafana/pull/3084.

**Comment by mtanda** [comment]
Thanks :smile:

**Comment by torkelo** [comment]
will close, this repo is deprecated (plugins should live in seperate repos)

**Pull request closed without merging**
