### PR TITLE
Update prometheus queries to use the v1 API, to be released with v0.15

### PR DESCRIPTION
**Pull request by pdf**
Also add a `label_values` query to allow templating.

I did not update the calls to `/api/metrics`, because there does not
seem to be a way to use wildcards with `/api/v1/series`, though I could
be missing something there.

### CODE REVIEW

**Comment by mtanda** [comment]
Hi, thank you for updating this plugin :smiley:

> I did not update the calls to /api/metrics, because there does not
seem to be a way to use wildcards with /api/v1/series

If you want to remove ```/api/metrics``` call, you can get same result by calling ```/api/v1/label/__name__/values```.

**Comment by pdf** [comment]
Ah, nice one, thanks @mtanda.  Updated.

**Comment by pdf** [comment]
I probably should have made it more clear, but the v1 API is only available with v0.15.0, which is currently at rc3, so this isn't available on the current stable.  I needed it to be able to do templating though.

**Comment by torkelo** [comment]
so you broke or is it just templating that will break for users who are no using 0.15?

**Comment by pdf** [comment]
These queries will not function on anything lower than v0.15.0, but I wanted to get this out there because once that's released, this plugin should standardize on it, because it will remain stable - the legacy API will likely go away at some point after v0.15.

**Pull request merged**
